### ISSUE TITLE
Try GitHub workflows for CI and other actions

### ISSUE THREAD

**Issue by iakov** [trikset/trik-desktop-gamepad#29]
Let's try https://help.github.com/en/articles/about-continuous-integration as CI for mac/Linux/Windows

**Comment by khodand** [comment]
Обсудили:
Попробовать сначала запускать травис затем AppVeyor

**Comment by iakov** [comment]
Уходим на GHA с тестовой сборкой для всех платформ, потому что у Аппвейора вообще непредсказуемая версия Qt https://www.appveyor.com/docs/windows-images-software/#qt.  
Получаем https://ci.appveyor.com/project/iakov/trik-desktop-gamepad/builds/40255906
Скрипт сборки можно взять как для checkapp
